esphome:
  name: ${device_id}  
  friendly_name: ${device_name}

sensor:
  # Uptime sensor
  - platform: uptime
    name: ${device_name} Uptime
    update_interval: 30s

  # Heartbeat Sensor
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    id: device_wifi_signal    
    name: ${device_name} WiFi Signal
    update_interval: 30s

switch:
  - platform: restart
    name: ${device_name} Restart

# binary_sensor:
#    - platform: status
#      name: ${device_name} Connectivity

# Get the time from Home Assistant to sync the onboard real-time-clock.
time:
  - platform: homeassistant
    id: home_time

# Home Assistant API (https://esphome.io/components/api)
api:  
  encryption:
    key: !secret api_key

# Over the air updates (https://esphome.io/components/ota)
ota:  
  password: !secret ota_password

# Enable Web server.
web_server:
  port: 80
  auth:
    username: !secret web_username
    password: !secret web_password

# Enable logging (https://esphome.io/components/logger)
logger:

# WIFI Details
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_id}.lannings.org # instead of using the default .local
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_id}"
    password: !secret web_password

# Fallback mechanism (https://esphome.io/components/captive_portal)
captive_portal: